# Generated by Django 3.2.6 on 2023-06-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inventory_no', models.TextField()),
                ('Location', models.TextField()),
                ('Owner', models.TextField()),
                ('Description', models.TextField()),
                ('Price', models.TextField()),
                ('Purchase_Date', models.TextField()),
                ('Active', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.TextField()),
                ('Full_Name', models.TextField()),
                ('Title', models.TextField()),
                ('Phone', models.TextField()),
                ('Email', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Owners',
            },
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
